name: 'Asana Github Pull Request - Milestone'
description: 'Links a PR with the milestone associated'
inputs:
  asana_token:
    description: 'Asana Token'
    required: true
  github_token:
    description: 'GitHub Token (automatically set by GitHub)'
    required: false
  workspace:
    description: 'Asana Workspace ID'
    required: true
branding:
  icon: 'chevron-right'
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'src/index.js'
