name: Asana Link
on:
  issues:
    types: [opened, closed, edited]
  pull_request:
    types: [opened, closed, edited, milestoned, demilestoned]
concurrency: ci-${{ github.repository }}
jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
      - name: Asana Github Link
        uses: ExodusMovement/asana-actions@2afce0004f5367a9d4f221a8bdebca536423d9d2
        with:
          asana_token: ${{ secrets.ASANA_TOKEN }}
          workspace: ${{ secrets.ASANA_WORKSPACE_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
