name: Asana Link
on:
  issues:
    types: [opened, closed, edited]
  pull_request:
    types: [opened, closed, edited, milestoned, demilestoned]
concurrency: ci-${{ github.repository }}
jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
      - name: Asana Github Link
        uses: ExodusMovement/asana-actions@e8f46f4327fda20555af4667a2a1206dc4261de8
        with:
          asana_token: ${{ secrets.ASANA_TOKEN }}
          workspace: ${{ secrets.ASANA_WORKSPACE_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
