name: Asana Link
on:
  issues:
    types: [opened, closed, edited]
  pull_request:
    types: [opened, closed, edited, milestoned]
jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install modules
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          yarn
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CI: true
      - name: Asana Github Link
        uses: ExodusMovement/asana-actions@4.3.0-draft2
        with:
          asana_token: ${{ secrets.ASANA_TOKEN }}
          workspace: ${{ secrets.ASANA_WORKSPACE_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
